#!/bin/sh

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
	"C-x")
		while read file; do
			lf -remote "send select '$file'"
			lf -remote "send toggle"
		done
		;;
	"C-comma")  rotate 270 ;;
	"C-period") rotate  90 ;;
	"C-slash")  rotate 180 ;;
esac
